// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twkldnxowgxqhsuqllsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3a2xkbnhvd2d4cWhzdXFsbHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDc0MDQsImV4cCI6MjA2MzY4MzQwNH0.b6h39CX_e5LLXKaS-0iLyKUN8d9-DBZ5XfScVfQyrog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);